---
name: "Lint And Build Nix Flake"
on:
  pull_request:
    paths:
      - "flake.nix"
      - "nix/**"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix run .#lint
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix run .#test
  binaries:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - run: nix build --print-build-logs .#logcli
      - run: nix build --print-build-logs .#loki
      - run: nix build --print-build-logs .#loki-canary
      - run: nix build --print-build-logs .#promtail
